// Auth
export const LOGIN = "LOGIN";
export const LOGOUT = "LOGOUT";

// Post Types
export const LOAD_POST_TYPES_LOADING = "LOAD_POST_TYPES_LOADING";
export const LOAD_POST_TYPES_SUCCESS = "LOAD_POST_TYPES_SUCCESS";
export const LOAD_POST_TYPES_ERROR = "LOAD_POST_TYPES_ERROR";

// Post
export const LOAD_POSTS_LOADING = "LOAD_POSTS_LOADING";
export const LOAD_POSTS_SUCCESS = "LOAD_POSTS_SUCCESS";
export const LOAD_MORE_POSTS_SUCCESS = "LOAD_MORE_POSTS_SUCCESS";
export const LOAD_POSTS_ERROR = "LOAD_POSTS_ERROR";
export const LIKE_POST = "LIKE_POST";
export const UNLIKE_POST = "UNLIKE_POST";
export const FAVOURITE_POST = "FAVOURITE_POST";
export const UNFAVOURITE_POST = "UNFAVOURITE_POST";
export const POST_DETAIL_DIRECT_NAVIGATION_SUCCESS = "POST_DETAIL_DIRECT_NAVIGATION_SUCCESS";
export const POST_DETAIL_DIRECT_NAVIGATION_ERROR = "POST_DETAIL_DIRECT_NAVIGATION_ERROR";
export const POST_DETAIL_DIRECT_NAVIGATION_LOADING = "POST_DETAIL_DIRECT_NAVIGATION_LOADING";
export const UPDATE_FILTERS = "UPDATE_FILTERS";

// Comment
export const LOAD_COMMENTS_LOADING = "LOAD_COMMENTS_LOADING";
export const LOAD_COMMENTS_SUCCESS = "LOAD_COMMENTS_SUCCESS";
export const LOAD_COMMENTS_ERROR = "LOAD_COMMENTS_ERROR";
export const ADD_COMMENT = "ADD_COMMENT";
export const LOAD_ADD_COMMENT = "LOAD_ADD_COMMENT";