// Auth
export const LOGIN = "LOGIN";
export const LOGOUT = "LOGOUT";

// Post Types
export const LOAD_POST_TYPES_LOADING = "LOAD_POST_TYPES_LOADING";
export const LOAD_POST_TYPES_SUCCESS = "LOAD_POST_TYPES_SUCCESS";
export const LOAD_POST_TYPES_ERROR = "LOAD_POST_TYPES_ERROR";

// Post
export const LOAD_POSTS_LOADING = "LOAD_POSTS_LOADING";
export const LOAD_POSTS_SUCCESS = "LOAD_POSTS_SUCCESS";
export const LOAD_POSTS_ERROR = "LOAD_POSTS_ERROR";