on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Build with dotnet
      run: dotnet build '.\WediumBackend\WediumBackend.sln'
    - name: Run tests
      env:
        DB_CONNECTION_STRING: ${{ secrets.DB_CONNECTION_STRING}}
        JWT_SECRET: ${{ secrets.JWT_SECRET}}
      run: dotnet test '.\WediumBackend\WediumBackend.sln' --verbosity normal